alias: Tesla - Carregamento Solar MPPT com Teslemetry
description: Ajuste automático da corrente do Tesla baseado na produção solar
trigger:
  - platform: time_pattern
    seconds: "/10"
condition:
  - condition: state
    entity_id: binary_sensor.modelx_charge_cable
    state: "on"
action:
  - variables:
      consumo: "{{ states('sensor.consumo_energy') | float(0) }}"
      current_actual: "{{ state_attr('climate.modelx', 'charging_current') | int(0) }}"
      max_amps: 16
      min_amps: 5
      # delta proporcional: cada 230W = 1A, mínimo 1A, máximo 5A
      delta: >-
        {% set d = (consumo / 230) | int %}
        {% if d == 0 and consumo != 0 %}
          {% if consumo > 0 %}-1{% else %}1{% endif %}
        {% else %}
          {% if d > 5 %}5{% elif d < -5 %}-5{% else %}{{d}}{% endif %}
        {% endif %}
      new_current: >-
        {% if consumo < 0 %}
          {{ [current_actual + (-delta), max_amps] | min }}
        {% elif consumo > 0 %}
          {{ [current_actual - delta, min_amps] | max }}
        {% else %}
          {{ current_actual }}
        {% endif %}
  - service: teslemetry.set_charging_current
    target:
      entity_id: climate.modelx
    data:
      current: "{{ new_current }}"
mode: single
