blueprint:
  name: Tesla - Carregamento Solar Inteligente (Teslemetry + Shelly)
  description: >
    Controla automaticamente o carregamento do Tesla de acordo com a produção solar medida por um Shelly.
    - Inicia carregamento se houver exportação solar suficiente.
    - Pausa carregamento se o consumo da rede ultrapassar 80 W por mais de 15 segundos.
    - Ajusta dinamicamente a corrente a cada 15 segundos para evitar flutuações.
  domain: automation
  input:
    sensor_consumo:
      name: Sensor de Consumo (Shelly)
      description: Sensor que mede o consumo/exportação (positivo = consumindo da rede, negativo = exportando)
      selector:
        entity:
          domain: sensor

    number_charge_current:
      name: Corrente de Carregamento (A)
      description: Entidade do tipo "number" usada para definir a corrente de carregamento do Tesla.
      selector:
        entity:
          domain: number

    binary_charge_cable:
      name: Cabo Conectado
      description: Indica se o cabo está plugado no Tesla.
      selector:
        entity:
          domain: binary_sensor

    tesla_vehicle:
      name: Veículo Tesla (Teslemetry)
      description: Entidade principal do veículo Tesla (ex: teslemetry.modelx)
      selector:
        entity:
          integration: teslemetry

    max_amps:
      name: Corrente Máxima (A)
      default: 16
      selector:
        number:
          min: 5
          max: 32
          unit_of_measurement: A

    min_amps:
      name: Corrente Mínima (A)
      default: 5
      selector:
        number:
          min: 1
          max: 16
          unit_of_measurement: A

    delta_positivo:
      name: Limiar de Consumo Positivo (W)
      description: Quando o consumo ultrapassa esse valor, a corrente será reduzida ou o carregamento será pausado.
      default: 80
      selector:
        number:
          min: 50
          max: 1000
          unit_of_measurement: W

    delta_negativo:
      name: Limiar de Exportação Negativa (W)
      description: Quando a exportação ultrapassa esse valor (negativo), o carregamento será iniciado.
      default: -200
      selector:
        number:
          min: -2000
          max: -50
          unit_of_measurement: W

    delay_ajuste:
      name: Tempo entre ajustes (segundos)
      description: Tempo mínimo entre alterações da corrente para evitar flutuações.
      default: 15
      selector:
        number:
          min: 5
          max: 120
          unit_of_measurement: s

variables:
  input_sensor_consumo: !input sensor_consumo
  input_number_charge_current: !input number_charge_current
  input_binary_charge_cable: !input binary_charge_cable
  input_tesla_vehicle: !input tesla_vehicle
  max_amps: !input max_amps
  min_amps: !input min_amps
  delta_pos: !input delta_positivo
  delta_neg: !input delta_negativo
  delay_ajuste: !input delay_ajuste

trigger:
  # Dispara sempre que o consumo muda por 10 segundos
  - platform: state
    entity_id: !input sensor_consumo
    for: "00:00:10"
    
  # Dispara se o sensor ficar "unknown" por 1 minuto
  - platform: state
    entity_id: !input sensor_consumo
    to: "unknown"
    for: "00:01:00"

condition:
  # Só roda se o cabo estiver conectado
  - condition: state
    entity_id: !input binary_charge_cable
    state: "on"

action:
  - variables:
      consumo: "{{ states(input_sensor_consumo) | float }}"
      amps_atual: "{{ states(input_number_charge_current) | int }}"

  - choose:
      # 1️⃣ Inicia carregamento e aumenta corrente se há exportação solar suficiente
      - conditions: "{{ consumo < delta_neg }}"
        sequence:
          - service: teslemetry.wake_up
            target:
              entity_id: !input tesla_vehicle
          - delay: "00:00:05"
          - service: teslemetry.start_charging
            target:
              entity_id: !input tesla_vehicle
          - delay: "00:00:05"
          - service: number.set_value
            target:
              entity_id: !input number_charge_current
            data:
              value: "{{ [amps_atual + 1, max_amps] | min }}"

      # 2️⃣ Reduz corrente se consumo positivo acima do limiar
      - conditions: "{{ consumo > delta_pos and amps_atual > min_amps }}"
        sequence:
          - service: number.set_value
            target:
              entity_id: !input number_charge_current
            data:
              value: "{{ [amps_atual - 1, min_amps] | max }}"

      # 3️⃣ Para carregamento se consumo > limiar positivo por mais de 15 segundos (histerese)
      - conditions:
          - condition: template
            value_template: "{{ consumo > delta_pos }}"
        sequence:
          - wait_for_trigger:
              - platform: template
                value_template: "{{ states(input_sensor_consumo) | float > delta_pos }}"
                for: "00:00:15"
          - service: teslemetry.stop_charging
            target:
              entity_id: !input tesla_vehicle

  # Delay entre ajustes para evitar oscilações rápidas
  - delay:
      seconds: !input delay_ajuste

mode: single
