alias: Tesla - Carregamento Solar Automático
description: Ajusta corrente do Tesla com base na produção solar
trigger:
  - platform: time_pattern
    seconds: "/10"  # executa a cada 10 segundos
condition:
  - condition: state
    entity_id: binary_sensor.modelx_charge_cable
    state: "on"
action:
  - variables:
      consumo: "{{ states('sensor.consumo_energy') | float(0) }}"
      amps_atual: "{{ states('number.charge_current') | int(0) }}"
      max_amps: 16
      min_amps: 5
      delta: "{{ (consumo / 230) | int }}"
  - choose:
      # Se estiver exportando energia (consumo < 0), aumenta corrente
      - conditions: "{{ consumo < 0 and amps_atual < max_amps }}"
        sequence:
          - service: number.set_value
            target:
              entity_id: number.charge_current
            data:
              value: "{{ [amps_atual + (-delta), max_amps] | min }}"
      # Se consumo positivo, reduz corrente
      - conditions: "{{ consumo > 0 and amps_atual > min_amps }}"
        sequence:
          - service: number.set_value
            target:
              entity_id: number.charge_current
            data:
              value: "{{ [amps_atual - delta, min_amps] | max }}"
mode: single
